[tasks.build-xoswap-browser-esm]
dir = "pkgs/xoswap"
hide = true
run = "bun build src --entry-naming [name].browser.m[ext] --format esm --minify --outdir dist --root src --sourcemap=inline --target browser"

[tasks.build-xoswap-browser-iife]
dir = "pkgs/xoswap"
hide = true
run = "bun build src --entry-naming [name].browser.iife.[ext] --format iife --minify --root src --outdir dist --sourcemap=inline --target browser"

[tasks.build-xoswap-bun-cjs]
dir = "pkgs/xoswap"
hide = true
run = "bun build src --entry-naming [name].bun.c[ext] --format cjs --minify --outdir dist --sourcemap=inline --root src --target bun"

[tasks.build-xoswap-bun-esm]
dir = "pkgs/xoswap"
hide = true
run = "bun build src --entry-naming [name].bun.m[ext] --format esm --minify --outdir dist --sourcemap=inline --root src --target bun"

[tasks.build-xoswap-node-cjs]
dir = "pkgs/xoswap"
hide = true
run = "bun build src --entry-naming [name].node.c[ext] --format cjs --minify --outdir dist --sourcemap=inline --root src --target node"

[tasks.build-xoswap-node-esm]
dir = "pkgs/xoswap"
hide = true
run = "bun build src --entry-naming [name].node.m[ext] --format esm --minify --outdir dist --sourcemap=inline --root src --target node"

[tasks.build-xoswap-types]
dir = "pkgs/xoswap"
hide = true
run = "tsc --project tsconfig.build.json"

[tasks.build-xoswap]
alias = 'bx'
description = "Bundle xoswap pkg"
run = ["rm -fr pkgs/xoswap/dist", "mise r build-xoswap-*"]

[tasks.build-cli]
alias = "bc"
description = "Build CLI"
dir = "pkgs/cli"
run = "bun build src --outdir dist --sourcemap=inline --target=bun"

[tasks.build-docs]
alias = 'bd'
description = 'Build docs'
run = "typedoc --githubPages true"

[tasks.serve-docs]
alias = 'sd'
description = 'Serve docs'
run = "serve docs"

[tasks.dev-cli]
alias = "dc"
description = "Run CLI in dev mode"
dir = "pkgs/cli"
run = "./bin/dev.js"

[tasks.hurl]
alias = "h"
description = "Run hurl requests"
dir = "pkgs/xoswap/test"
run = 'hurl --variable app=xoswap-sdk-test'
quiet = true

[tasks.hurl-test]
alias = "ht"
description = "Run hurl tests"
dir = "pkgs/xoswap/test"
hide = true
run = 'hurl --variable app=xoswap-sdk-test --test *.hurl'

[tasks.test-cli]
alias = "tc"
dir = "pkgs/cli"
description = "Run CLI tests"
run = "bun run mocha --forbid-only \"test/**/*.test.ts\""

[tasks.test-xoswap]
alias = "tx"
dir = "pkgs/xoswap"
description = 'Run xoswap bun tests'
run = "bun test"

[tasks.test-xoswap-watch]
alias = "tx"
dir = "pkgs/xoswap"
description = 'Run xoswap bun tests in watch mode'
run = "bun test --watch"

[tasks.test]
alias = "t"
description = "Run all tests"
run = "mise run test-*"
quiet = true

[tools]
node = "23"
pnpm = "latest"
"npm:oclif" = "latest"
"cargo:convco" = "latest"
"npm:@biomejs/biome" = "latest"
hk = "latest"
dprint = "latest"
pkl = "latest"
"npm:typescript" = "latest"
bun = "latest"
"npm:typedoc" = "latest"
"npm:serve" = "latest"
