[tasks.dev-cli]
alias = "dc"
description = "Run CLI in dev mode"
dir = "pkgs/cli"
run = "./bin/dev.js"

[tools]
node = "23"
pnpm = "latest"
"npm:oclif" = "latest"
"cargo:convco" = "latest"
"npm:@biomejs/biome" = "latest"
hk = "latest"
dprint = "latest"
pkl = "latest"
"npm:typescript" = "latest"
bun = "latest"
