[tasks.dev]
alias = "d"
description = "Run CLI in dev mode"
run = "$MISE_PROJECT_ROOT/bin/dev.js"

[tools]
node = "23"
pnpm = "latest"
"npm:oclif" = "latest"
"cargo:convco" = "latest"
"npm:@biomejs/biome" = "latest"
hk = "latest"
dprint = "latest"
pkl = "latest"
"npm:typescript" = "latest"
